name: Upload Package with render

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  common_steps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" = "ubuntu-latest" ]; then
            sudo apt-get install libsdl2-dev
            export CFLAGS="-I/usr/include/SDL2" 
            export LDFLAGS="-L/usr/lib" 
          elif [ "${{ runner.os }}" = "windows-latest" ]; then
            mkdir SDL2
            curl -L https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip -o SDL2/SDL2.zip
            unzip SDL2/SDL2.zip -d SDL2
            echo "::set-env name=CFLAGS::\"-I$(Get-Location)/SDL2/include\""
            echo "::set-env name=LDFLAGS::\"-L$(Get-Location)/SDL2/lib\""
          elif [ "${{ runner.os }}" = "macos-latest" ]; then
            brew update
            brew install sdl2
          fi
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          cd render
          python -m build
        id: build
      - name: Publish package
        if: success()  # Only publish if build succeeded
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
